baseurl = "https://codegangsta.io"
languageCode = "en-us"
title = "codegangsta.io"
theme = "codegangsta"
disqusShortname = "codegangsta"

[author]
name = "Jeremy Saenz"

[params]
theme = "theme-base-0d"
tagline = "Awesome tools and screencasts for Go programmers."
highlight = "github"
github = "github.com/codegangsta"

[permalinks]
# Optional. Change the permalink format for the 'post' content type.
# The format shown here is the same one Jekyll/Octopress uses by default.
post = "/blog/:year/:month/:day/:filename/"
